### ISSUE TITLE
Apply a different IP verification interval to each specific policy *Suggestion from Andrew-E at SNBForums* 

### ISSUE THREAD

**Issue by computersteve** [Ranger802004/asusmerlin#40]
Please create a feature to apply different IP verification polling intervals for each specific policies: for example, A policy for YouTube should be polled every 10 minutes or less because of the many ips that service uses. While other policies (services) do not need any interval at all or require a very infrequent update interval, because they have very few IPs and infrequent verification  is required.

**Comment by Ranger802004** [comment]
As simple as this sounds, it can be cause more complications at face value doing this.  The querypolicy and queryasn functions lock script execution from any other instances when they are running, this can cause extra executions of querypolicy at different intervals to not work due to the locking file mechanisms to prevent duplicate instances of the script running.  What may be possible is to set up a parameters for each policy, and when the querypolicy all CRON job runs, it will check that policy if it is outside of the update interval timeframe when being executed.  I will have to look into this and see what is possible.
