### ISSUE TITLE
Failover high cpu usage

### ISSUE THREAD

**Issue by eduardoibarra960** [Ranger802004/asusmerlin#51]
Pretty high overall cpu usage (85-95%) after installing this on RT-AC88U on 386.14. Entire router got pretty slow on boot and gui usage. top command shows mtdblock3 using plenty of cpu.

2-10% overall cpu usage after I uninstalled it.

**Comment by Ranger802004** [comment]
The first thing you'll need to do is collect debug logs from WAN Failover and deliver those here.

**Comment by eduardoibarra960** [comment]
[wan-failover-2024-11-08-18%3A53%3A32-GMT.log](https://github.com/user-attachments/files/17685448/wan-failover-2024-11-08-18.3A53.3A32-GMT.log)

**Comment by Ranger802004** [comment]
I'm seeing various routing issues from the initial failback from WAN1 to WAN0 at bootup and failures to add default routes in the log.  Also the log appears to be missing some info but WAN Failover is going into a disabled state but the log to review why is cut off.  Try adding a boot delay timer (180 seconds) and reboot the router and see if it properly loads up.  Also, the CPU spike is being caused by the failover loop having to constantly retry adding the default route for WAN0 which is failing so it loops until it hits the failover timeout.

**Comment by Ranger802004** [comment]
Closing for no response.
